name: Deploy to Production

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v2
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{secrets.GIT_TOKEN}}

      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: 8000
          envkey_NODE_ENV: development
          envkey_DB_DATABASE: ${{secrets.DB_DATABASE}}
          envkey_DB_USERNAME: ${{secrets.DB_USERNAME}}
          envkey_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          envkey_DB_PORT: ${{secrets.DB_PORT}}

          file_name: .env

      - name: Get Semantic Versioning
        id: docker-image-version
        run: |
          VERSION=`cat ./version.txt`-${{github.run_id}}
          echo "::set-output name=version::$VERSION"

      - name: Build, Push image to Github Container Registry
        env:
          DOCKER_REGISTRY: ghcr.io/javastudybest
          DOCKER_REPOSITORY: express_practice
          IMAGE_TAG: ${{steps.docker-image-version.outputs.version}}
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          echo -e "IMAGE=$DOCKER_REGISTRY/$DOCKER_REPOSITORY\nTAG=$IMAGE_TAG"

      - name: Zip deploy.Zip
        run: zip -r deploy.zip deploy

      - name: Upload deploy.zip
        uses: actions/upload-artifact@v2
        with:
          name: deploy.zip
          path: deploy.zip

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Downloa deploy.zip
        uses: actions/download-artifact@v2
        with:
          name: deploy.zip

      - name: run server
        run: |
          unzip -o ./deploy.zip
          cd deploy/
          sh ./run.sh
